// publish — open (or refresh) the PR for the reviewed change, then relabel.
//
// Assembles the PR body from AGENT-authored text (implement.prBody, the
// revise log, self-review concerns) — this script writes NO prose, it only
// concatenates and templates. Draft-vs-ready is decided by the final review
// state:
//   ship               -> ready-for-review, clean
//   flag               -> ready-for-review, FYI notes appended
//   capped revise       -> DRAFT, "must fix before merge" notes appended
//
// Idempotent: reuses an existing open PR for the branch instead of erroring.
//
// Reads:  /output/input.json (steps.implement, steps.self-review, steps.revise),
//         env GITHUB_TOKEN, FULLSTACK_REPO, REVIEW_MAX
// Writes: /output/result.json

import { readFileSync, writeFileSync } from 'node:fs';

const REPO = process.env.FULLSTACK_REPO || 'Appsilon/mediforce';
const [OWNER, NAME] = REPO.split('/');
const REVIEW_MAX = Number(process.env.REVIEW_MAX || '2');
const IN_PROGRESS = 'fullstack:in-progress';
const PR_OPEN = 'fullstack:pr-open';

function ghHeaders() {
  const h = { Accept: 'application/vnd.github+json', 'User-Agent': 'mediforce-fullstack-bot' };
  if (process.env.GITHUB_TOKEN) h.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  return h;
}

async function gh(path, init) {
  const res = await fetch(`https://api.github.com${path}`, { headers: ghHeaders(), ...init });
  if (!res.ok && !(init?.method === 'DELETE' && res.status === 404)) {
    throw new Error(`GitHub ${res.status} ${init?.method || 'GET'} ${path}: ${(await res.text()).slice(0, 200)}`);
  }
  return res.status === 204 || res.status === 404 ? null : res.json();
}

/** Decide draft flag + which notes heading applies. Pure. */
export function reviewOutcome(selfReview, reviewCount, reviewMax) {
  const verdict = selfReview?.verdict;
  const capped = verdict === 'revise' && (reviewCount ?? 0) >= reviewMax;
  if (capped) return { draft: true, heading: '### ⚠️ Must fix before merge' };
  if (verdict === 'flag') return { draft: false, heading: '### 🤖 self-review notes (FYI)' };
  return { draft: false, heading: null };
}

/** Assemble the PR body from agent-written pieces. Pure. */
export function buildPrBody(implement, selfReview, revise, outcome) {
  const parts = [implement.prBody || implement.summary || ''];
  const log = revise?.reviseLog;
  if (Array.isArray(log) && log.length > 0) {
    parts.push('### 🔁 Review & revision history', log.map((l) => `- ${l}`).join('\n'));
  }
  const concerns = selfReview?.concerns;
  if (outcome.heading && Array.isArray(concerns) && concerns.length > 0) {
    parts.push(outcome.heading, concerns.map((c) => `- ${c}`).join('\n'));
  }
  parts.push('---', '🤖 generated by mediforce-fullstack');
  return parts.filter(Boolean).join('\n\n');
}

async function main() {
  const input = JSON.parse(readFileSync('/output/input.json', 'utf-8'));
  const implement = input?.steps?.implement || {};
  const selfReview = input?.steps?.['self-review'] || {};
  const revise = input?.steps?.revise || {};
  const issueNumber = implement.issueNumber;
  const branch = implement.branch;
  const baseBranch = implement.baseBranch || 'main';
  if (!issueNumber || !branch) throw new Error('publish: missing implement.issueNumber or implement.branch');

  const outcome = reviewOutcome(selfReview, revise.reviewCount, REVIEW_MAX);
  const body = buildPrBody(implement, selfReview, revise, outcome);

  const existing = await gh(`/repos/${REPO}/pulls?head=${OWNER}:${encodeURIComponent(branch)}&state=open`);
  let pr;
  if (Array.isArray(existing) && existing.length > 0) {
    pr = await gh(`/repos/${REPO}/pulls/${existing[0].number}`, {
      method: 'PATCH',
      headers: { ...ghHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify({ body }),
    });
  } else {
    pr = await gh(`/repos/${REPO}/pulls`, {
      method: 'POST',
      headers: { ...ghHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: implement.prTitle, head: branch, base: baseBranch, body, draft: outcome.draft }),
    });
  }

  // Swap the lease for the done-state label, then comment the link.
  await gh(`/repos/${REPO}/issues/${issueNumber}/labels`, {
    method: 'POST',
    headers: { ...ghHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify({ labels: [PR_OPEN] }),
  });
  await gh(`/repos/${REPO}/issues/${issueNumber}/labels/${encodeURIComponent(IN_PROGRESS)}`, { method: 'DELETE' });
  await gh(`/repos/${REPO}/issues/${issueNumber}/comments`, {
    method: 'POST',
    headers: { ...ghHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify({ body: `🤖 Opened ${outcome.draft ? 'draft ' : ''}PR ${pr.html_url} for this issue. — mediforce-fullstack` }),
  }).catch((err) => console.error(`publish: link comment failed: ${err.message}`));

  writeFileSync('/output/result.json', JSON.stringify({ issueNumber, prUrl: pr.html_url, prNumber: pr.number, branch, draft: outcome.draft }));
  console.log(`publish: #${issueNumber} → ${outcome.draft ? 'draft ' : ''}PR ${pr.html_url}`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error('publish crashed:', err && err.stack ? err.stack : String(err));
    process.exit(1);
  });
}
