# =============================================================================
# CDISC Pilot 01 — Interactive Clinical Data Explorer (teal)
# Study: CDISCPILOT01 — Xanomeline vs Placebo in Alzheimer's Disease
# Generated by: adam-to-teal skill
# =============================================================================

library(teal)
library(teal.data)
library(teal.modules.general)
library(teal.modules.clinical)
library(dplyr)

# ---- Data loading ----

# Resolve data directory relative to this app.R file
APP_DIR <- if (interactive() && requireNamespace("rstudioapi", quietly = TRUE)) {
  dirname(rstudioapi::getSourceEditorContext()$path)
} else {
  tryCatch(dirname(sys.frame(1)$ofile), error = function(e) getwd())
}
DATA_DIR <- normalizePath(file.path(APP_DIR, "..", "adam", "data"), mustWork = FALSE)
if (!dir.exists(DATA_DIR)) {
  DATA_DIR <- normalizePath("outputs/cdiscpilot01/adam/data", mustWork = FALSE)
}
if (!dir.exists(DATA_DIR)) stop("Cannot find ADaM data directory. Set working directory to project root.")

data <- teal_data()
data <- within(data, {
  library(dplyr)

  DATA_DIR <- DATA_DIR_PLACEHOLDER

  read_adam <- function(name, data_dir) {
    csv_path <- file.path(data_dir, paste0(name, ".csv"))
    if (file.exists(csv_path)) {
      read.csv(csv_path, stringsAsFactors = FALSE)
    } else {
      stop(paste("Dataset", name, "not found in", data_dir))
    }
  }

  # --- Load datasets ---
  ADSL <- read_adam("adsl", DATA_DIR)
  ADAE <- read_adam("adae", DATA_DIR)
  ADLB <- read_adam("adlb", DATA_DIR)
  ADVS <- read_adam("advs", DATA_DIR)
  ADEX <- read_adam("adex", DATA_DIR)
  ADCM <- read_adam("adcm", DATA_DIR)
  ADQSADAS <- read_adam("adqsadas", DATA_DIR)
  ADQSCIBC <- read_adam("adqscibc", DATA_DIR)
  ADQSNPIX <- read_adam("adqsnpix", DATA_DIR)
  ADTTE <- read_adam("adtte", DATA_DIR)

  # --- Factor conversion (required by teal modules) ---

  factorize <- function(df, vars) {
    for (v in intersect(vars, names(df))) {
      df[[v]] <- factor(df[[v]])
    }
    df
  }

  common_factors <- c(
    "TRT01P", "TRT01A", "TRT01PN", "TRT01AN",
    "TRTP", "TRTA",
    "SEX", "RACE", "ETHNIC", "AGEGR1", "AGEGR1N",
    "SAFFL", "ITTFL", "EFFFL",
    "COMP8FL", "COMP16FL", "COMP24FL",
    "EOSSTT", "DCSREAS", "SITEGR1", "SITEID",
    "BMIBLGR1", "DURDSGR1", "DTHFL", "COUNTRY"
  )

  ae_factors <- c(
    "AEBODSYS", "AEDECOD", "AESEV", "AESER", "AEREL",
    "AEACN", "AEOUT", "TRTEMFL", "AOCCFL", "AOCCSFL", "AOCCPFL",
    "CQ01NAM"
  )

  bds_factors <- c(
    "PARAMCD", "PARAM", "AVISIT", "ABLFL", "ANL01FL",
    "ANRIND", "BNRIND", "SHIFT1"
  )

  tte_factors <- c("PARAMCD", "PARAM", "CNSR", "EVNTDESC", "CNSDTDSC")

  cm_factors <- c("CMDECOD", "CMCLAS", "CONCOMFL", "PREFL", "ONTRTFL")

  ADSL <- factorize(ADSL, common_factors)
  ADAE <- factorize(factorize(ADAE, common_factors), ae_factors)
  ADLB <- factorize(factorize(ADLB, common_factors), bds_factors)
  ADVS <- factorize(factorize(ADVS, common_factors), bds_factors)
  ADEX <- factorize(factorize(ADEX, common_factors), bds_factors)
  ADCM <- factorize(factorize(ADCM, common_factors), cm_factors)
  ADQSADAS <- factorize(factorize(ADQSADAS, common_factors), bds_factors)
  ADQSCIBC <- factorize(factorize(ADQSCIBC, common_factors), bds_factors)
  ADQSNPIX <- factorize(factorize(ADQSNPIX, common_factors), bds_factors)
  ADTTE <- factorize(factorize(ADTTE, common_factors), tte_factors)

  # Filter out Screen Failures for cleaner display
  ADSL <- ADSL %>% filter(ITTFL == "Y" | SAFFL == "Y")
}, DATA_DIR_PLACEHOLDER = DATA_DIR)

# Join keys
join_keys(data) <- default_cdisc_join_keys[
  c("ADSL", "ADAE", "ADLB", "ADVS", "ADEX", "ADCM", "ADTTE")
]
# Add keys for QS datasets (same structure as BDS)
join_keys(data)["ADQSADAS", "ADQSADAS"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
join_keys(data)["ADSL", "ADQSADAS"] <- c("STUDYID", "USUBJID")
join_keys(data)["ADQSCIBC", "ADQSCIBC"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
join_keys(data)["ADSL", "ADQSCIBC"] <- c("STUDYID", "USUBJID")
join_keys(data)["ADQSNPIX", "ADQSNPIX"] <- c("STUDYID", "USUBJID", "PARAMCD", "AVISIT")
join_keys(data)["ADSL", "ADQSNPIX"] <- c("STUDYID", "USUBJID")

data <- verify(data)

# ---- Module configuration ----
# Note: paramcd and visit_var in clinical modules require value_choices() (not plain vectors)
# because the dev teal API routes them through cs_to_des_filter -> filter_spec.

app <- init(
  data = data,
  modules = modules(

    # --- General Exploration ---
    modules(
      label = "Data Exploration",
      tm_data_table("Data Table"),
      tm_variable_browser("Variable Browser"),
      tm_g_scatterplot(
        label = "Scatterplot",
        x = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            choices = c("AGE", "WEIGHTBL", "HEIGHTBL", "BMIBL", "MMSETOT", "DURDIS", "EDUCLVL"),
            selected = "AGE"
          )
        ),
        y = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            choices = c("AGE", "WEIGHTBL", "HEIGHTBL", "BMIBL", "MMSETOT", "DURDIS", "EDUCLVL"),
            selected = "BMIBL"
          )
        ),
        color_by = data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            choices = c("TRT01P", "SEX", "RACE", "AGEGR1"),
            selected = "TRT01P"
          )
        )
      )
    ),

    # --- Demographics ---
    modules(
      label = "Demographics",
      tm_t_summary(
        label = "Demographic Table",
        dataname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        summarize_vars = choices_selected(
          choices = variable_choices("ADSL", c(
            "AGE", "AGEGR1", "SEX", "RACE", "ETHNIC",
            "WEIGHTBL", "HEIGHTBL", "BMIBL", "BMIBLGR1",
            "DURDIS", "DURDSGR1", "EDUCLVL", "MMSETOT"
          )),
          selected = c("AGE", "AGEGR1", "SEX", "RACE")
        )
      ),
      tm_t_summary(
        label = "Disposition",
        dataname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        summarize_vars = choices_selected(
          choices = variable_choices("ADSL", c("EOSSTT", "DCSREAS", "COMP8FL", "COMP16FL", "COMP24FL")),
          selected = c("EOSSTT", "DCSREAS")
        )
      )
    ),

    # --- Safety ---
    modules(
      label = "Safety",
      tm_t_events_summary(
        label = "AE Overview",
        dataname = "ADAE",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        )
      ),
      tm_t_events(
        label = "AE by SOC and PT",
        dataname = "ADAE",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        ),
        hlt = choices_selected(
          choices = variable_choices("ADAE", "AEBODSYS"),
          selected = "AEBODSYS"
        ),
        llt = choices_selected(
          choices = variable_choices("ADAE", "AEDECOD"),
          selected = "AEDECOD"
        ),
        event_type = "adverse event"
      ),
      tm_t_events_by_grade(
        label = "AE by Severity",
        dataname = "ADAE",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        ),
        hlt = choices_selected(
          choices = variable_choices("ADAE", "AEBODSYS"),
          selected = "AEBODSYS"
        ),
        llt = choices_selected(
          choices = variable_choices("ADAE", "AEDECOD"),
          selected = "AEDECOD"
        ),
        grade = choices_selected(
          choices = variable_choices("ADAE", "AESEV"),
          selected = "AESEV"
        )
      ),
      tm_t_shift_by_arm(
        label = "Lab Shift Table",
        dataname = "ADLB",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADLB", "PARAMCD", "PARAM"),
          selected = "ALT"
        ),
        visit_var = choices_selected(
          choices = value_choices("ADLB", "AVISIT", "AVISIT"),
          selected = "SCREENING 1"
        ),
        aval_var = choices_selected(
          choices = variable_choices("ADLB", "ANRIND"),
          selected = "ANRIND"
        ),
        baseline_var = choices_selected(
          choices = variable_choices("ADLB", "BNRIND"),
          selected = "BNRIND"
        ),
        treatment_flag_var = choices_selected(
          choices = variable_choices("ADLB", "ANL01FL"),
          selected = "ANL01FL"
        ),
        treatment_flag = choices_selected(choices = "Y", selected = "Y")
      ),
      tm_g_lineplot(
        label = "Lab Values Over Time",
        dataname = "ADLB",
        parentname = "ADSL",
        group_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        ),
        x = choices_selected(
          choices = variable_choices("ADLB", c("AVISIT", "AVISITN", "ADY")),
          selected = "AVISIT"
        ),
        y = choices_selected(
          choices = variable_choices("ADLB", c("AVAL", "CHG")),
          selected = "AVAL"
        ),
        param = choices_selected(
          choices = value_choices("ADLB", "PARAMCD", "PARAM"),
          selected = "ALT"
        )
      ),
      tm_g_lineplot(
        label = "Vital Signs Over Time",
        dataname = "ADVS",
        parentname = "ADSL",
        group_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        ),
        x = choices_selected(
          choices = variable_choices("ADVS", c("AVISIT", "AVISITN", "ADY")),
          selected = "AVISIT"
        ),
        y = choices_selected(
          choices = variable_choices("ADVS", c("AVAL", "CHG")),
          selected = "AVAL"
        ),
        param = choices_selected(
          choices = value_choices("ADVS", "PARAMCD", "PARAM"),
          selected = "SYSBP_SUPINE"
        )
      )
    ),

    # --- Efficacy ---
    modules(
      label = "Efficacy",
      tm_t_summary_by(
        label = "ADAS-Cog Summary",
        dataname = "ADQSADAS",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        summarize_vars = choices_selected(
          choices = variable_choices("ADQSADAS", c("AVAL", "CHG")),
          selected = "CHG"
        ),
        by_vars = choices_selected(
          choices = variable_choices("ADQSADAS", c("AVISIT", "AVISITN")),
          selected = "AVISIT"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADQSADAS", "PARAMCD", "PARAM"),
          selected = "ACTOT"
        )
      ),
      tm_g_lineplot(
        label = "ADAS-Cog Over Time",
        dataname = "ADQSADAS",
        parentname = "ADSL",
        group_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        x = choices_selected(
          choices = variable_choices("ADQSADAS", c("AVISIT", "AVISITN", "ADY")),
          selected = "AVISIT"
        ),
        y = choices_selected(
          choices = variable_choices("ADQSADAS", c("AVAL", "CHG")),
          selected = "CHG"
        ),
        param = choices_selected(
          choices = value_choices("ADQSADAS", "PARAMCD", "PARAM"),
          selected = "ACTOT"
        )
      ),
      tm_t_ancova(
        label = "ADAS-Cog ANCOVA",
        dataname = "ADQSADAS",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        avisit = choices_selected(
          choices = value_choices("ADQSADAS", "AVISIT", "AVISIT"),
          selected = "Week 24"
        ),
        aval_var = choices_selected(
          choices = variable_choices("ADQSADAS", c("CHG", "AVAL")),
          selected = "CHG"
        ),
        cov_var = choices_selected(
          choices = variable_choices("ADQSADAS", c("BASE", "SITEGR1")),
          selected = "BASE"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADQSADAS", "PARAMCD", "PARAM"),
          selected = "ACTOT"
        ),
        conf_level = choices_selected(choices = c(0.95, 0.90, 0.80), 0.95, keep_order = TRUE)
      ),
      tm_t_summary_by(
        label = "CIBIC+ Summary",
        dataname = "ADQSCIBC",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        summarize_vars = choices_selected(
          choices = variable_choices("ADQSCIBC", c("AVAL", "CHG")),
          selected = "AVAL"
        ),
        by_vars = choices_selected(
          choices = variable_choices("ADQSCIBC", c("AVISIT", "AVISITN")),
          selected = "AVISIT"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADQSCIBC", "PARAMCD", "PARAM"),
          selected = "CIBIC"
        )
      ),
      tm_t_summary_by(
        label = "NPI-X Summary",
        dataname = "ADQSNPIX",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        summarize_vars = choices_selected(
          choices = variable_choices("ADQSNPIX", c("AVAL", "CHG")),
          selected = "CHG"
        ),
        by_vars = choices_selected(
          choices = variable_choices("ADQSNPIX", c("AVISIT", "AVISITN")),
          selected = "AVISIT"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADQSNPIX", "PARAMCD", "PARAM"),
          selected = "NPTOT"
        )
      ),
      tm_g_km(
        label = "KM: Time to Derm Event",
        dataname = "ADTTE",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADTTE", "PARAMCD", "PARAM"),
          selected = "TTDERM"
        ),
        strata_var = choices_selected(
          choices = variable_choices("ADSL", c("SEX", "AGEGR1", "RACE")),
          selected = NULL
        ),
        facet_var = choices_selected(
          choices = variable_choices("ADSL", c("SEX", "AGEGR1")),
          selected = NULL
        )
      ),
      tm_t_tte(
        label = "TTE Summary",
        dataname = "ADTTE",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADTTE", "PARAMCD", "PARAM"),
          selected = "TTDERM"
        ),
        strata_var = choices_selected(
          choices = variable_choices("ADSL", c("SEX", "AGEGR1", "RACE")),
          selected = NULL
        ),
        aval_var = choices_selected(
          choices = variable_choices("ADTTE", "AVAL"),
          selected = "AVAL",
          fixed = TRUE
        ),
        cnsr_var = choices_selected(
          choices = variable_choices("ADTTE", "CNSR"),
          selected = "CNSR",
          fixed = TRUE
        ),
        time_points = choices_selected(
          choices = c(30, 60, 90, 120, 150, 180),
          selected = c(90, 180)
        ),
        time_unit_var = choices_selected(
          choices = variable_choices("ADTTE", "PARAMCD"),
          selected = "PARAMCD",
          fixed = TRUE
        ),
        event_desc_var = choices_selected(
          choices = "EVNTDESC",
          selected = "EVNTDESC",
          fixed = TRUE
        )
      ),
      tm_g_forest_tte(
        label = "Forest Plot: TTE Subgroups",
        dataname = "ADTTE",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADTTE", "PARAMCD", "PARAM"),
          selected = "TTDERM"
        ),
        subgroup_var = choices_selected(
          choices = variable_choices("ADSL", c("SEX", "AGEGR1", "RACE")),
          selected = c("SEX", "AGEGR1")
        ),
        strata_var = choices_selected(
          choices = variable_choices("ADSL", c("SEX", "AGEGR1", "RACE")),
          selected = NULL
        ),
        aval_var = choices_selected(
          choices = variable_choices("ADTTE", "AVAL"),
          selected = "AVAL"
        ),
        cnsr_var = choices_selected(
          choices = variable_choices("ADTTE", "CNSR"),
          selected = "CNSR"
        )
      )
    ),

    # --- Exposure ---
    modules(
      label = "Exposure",
      tm_t_summary_by(
        label = "Exposure Summary",
        dataname = "ADEX",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01P", "TRT01A")),
          selected = "TRT01P"
        ),
        summarize_vars = choices_selected(
          choices = variable_choices("ADEX", "AVAL"),
          selected = "AVAL"
        ),
        by_vars = choices_selected(
          choices = variable_choices("ADEX", c("AVISIT", "AVISITN")),
          selected = "AVISIT"
        ),
        paramcd = choices_selected(
          choices = value_choices("ADEX", "PARAMCD", "PARAM"),
          selected = "TRTDUR"
        )
      )
    ),

    # --- Concomitant Medications ---
    modules(
      label = "Concomitant Meds",
      tm_t_events(
        label = "CM by Class and Term",
        dataname = "ADCM",
        parentname = "ADSL",
        arm_var = choices_selected(
          choices = variable_choices("ADSL", c("TRT01A", "TRT01P")),
          selected = "TRT01A"
        ),
        hlt = choices_selected(
          choices = variable_choices("ADCM", "CMCLAS"),
          selected = "CMCLAS"
        ),
        llt = choices_selected(
          choices = variable_choices("ADCM", "CMDECOD"),
          selected = "CMDECOD"
        ),
        event_type = "concomitant medication"
      )
    )
  ),

  # Default filter: ITT population
  filter = teal_slices(
    teal_slice("ADSL", "ITTFL", selected = "Y"),
    teal_slice("ADSL", "SAFFL", selected = "Y")
  )
)

# App header/footer
app <- modify_header(app, tags$h3("CDISCPILOT01 — Xanomeline vs Placebo in Alzheimer's Disease"))
app <- modify_footer(app, tags$p("Generated by adam-to-teal skill | Data: CDISC Pilot 01 ADaM"))

shinyApp(app$ui, app$server)
