#!/usr/bin/env python3
"""Bootstrap E2E test environment for remote/CI agents.

Prepares everything needed to run Playwright E2E tests with Firebase emulators
in environments where manual setup hasn't been done (Claude Code remote, CI, etc).

Usage:
    python3 packages/platform-ui/scripts/bootstrap_e2e.py
    # Then run tests:
    cd packages/platform-ui && pnpm test:e2e:auth
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

PLATFORM_UI = Path(__file__).resolve().parent.parent
ROOT = PLATFORM_UI.parent.parent

ENV_LOCAL = PLATFORM_UI / ".env.local"
FIREBASE_CONFIG = Path("/tmp/firebase-e2e.json")
# Emulator ports
AUTH_PORT = 9099
FIRESTORE_PORT = 8080
DEV_SERVER_PORT = 9007

# Colors for terminal output
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
RESET = "\033[0m"
BOLD = "\033[1m"


def log(msg: str, color: str = GREEN) -> None:
    print(f"{color}{BOLD}[bootstrap]{RESET} {msg}")


def check_port(port: int) -> bool:
    """Check if a port is already in use."""
    try:
        urllib.request.urlopen(f"http://127.0.0.1:{port}", timeout=2)
        return True
    except Exception:
        return False


def ensure_env_local() -> bool:
    """Create .env.local with demo Firebase credentials if missing."""
    if ENV_LOCAL.exists():
        log(f".env.local already exists at {ENV_LOCAL}", YELLOW)
        return False

    ENV_LOCAL.write_text(
        "# Firebase emulator mode — demo credentials\n"
        "# Auto-generated by bootstrap script. Safe to delete.\n"
        "NEXT_PUBLIC_FIREBASE_API_KEY=fake-api-key-for-emulators\n"
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-mediforce.firebaseapp.com\n"
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-mediforce\n"
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-mediforce.appspot.com\n"
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000\n"
        "NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000\n"
        "OPENROUTER_API_KEY=fake-openrouter-key\n"
        "PLATFORM_API_KEY=test-api-key\n"
    )
    log(f"Created {ENV_LOCAL} with demo credentials")
    return True


def ensure_firebase_config() -> None:
    """Create Firebase emulator config without UI (avoids proxy/download issues)."""
    config = {
        "firestore": {"rules": "firestore.rules"},
        "emulators": {
            "auth": {"port": AUTH_PORT},
            "firestore": {"port": FIRESTORE_PORT},
            "ui": {"enabled": False},
        },
    }
    FIREBASE_CONFIG.write_text(json.dumps(config, indent=2))
    log(f"Firebase emulator config written to {FIREBASE_CONFIG}")


def start_emulators() -> subprocess.Popen[bytes] | None:
    """Start Firebase emulators if not already running."""
    if check_port(AUTH_PORT) and check_port(FIRESTORE_PORT):
        log("Firebase emulators already running", YELLOW)
        return None

    if not shutil.which("firebase"):
        log("firebase CLI not found — install with: npm i -g firebase-tools", RED)
        sys.exit(1)

    # Strip proxy env vars that cause Firebase CLI to crash with circular JSON errors
    clean_env = {
        k: v
        for k, v in os.environ.items()
        if not k.startswith("GLOBAL_AGENT") and k != "JAVA_TOOL_OPTIONS"
    }
    # Keep JAVA_HOME if set, but remove proxy flags from JAVA_TOOL_OPTIONS
    if "JAVA_HOME" in os.environ:
        clean_env["JAVA_HOME"] = os.environ["JAVA_HOME"]

    log("Starting Firebase emulators (auth + firestore)...")
    proc = subprocess.Popen(
        [
            "firebase",
            "emulators:start",
            "--project", "demo-mediforce",
            "--only", "auth,firestore",
            "--config", str(FIREBASE_CONFIG),
        ],
        cwd=str(PLATFORM_UI),
        env=clean_env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    # Wait for emulators to be ready
    for attempt in range(30):
        if check_port(AUTH_PORT) and check_port(FIRESTORE_PORT):
            log("Firebase emulators ready")
            return proc
        time.sleep(1)

    log("Firebase emulators failed to start within 30s", RED)
    proc.kill()
    sys.exit(1)


def ensure_playwright() -> None:
    """Install Playwright browsers if needed."""
    result = subprocess.run(
        ["npx", "playwright", "install", "--with-deps", "chromium"],
        cwd=str(PLATFORM_UI),
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        log("Playwright chromium ready")
    else:
        log(f"Playwright install warning: {result.stderr[:200]}", YELLOW)


def ensure_ffmpeg() -> None:
    """Install ffmpeg if not available (needed for GIF conversion)."""
    if shutil.which("ffmpeg"):
        log("ffmpeg already available", YELLOW)
        return

    log("Installing ffmpeg...")
    result = subprocess.run(
        ["apt-get", "install", "-y", "-qq", "ffmpeg"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        log("ffmpeg installed")
    else:
        log("ffmpeg install failed (non-critical — GIF conversion won't work)", YELLOW)


def kill_port(port: int) -> None:
    """Kill any process on a given port."""
    subprocess.run(
        ["fuser", "-k", f"{port}/tcp"],
        capture_output=True,
    )


def main() -> None:
    log("Bootstrapping E2E environment...")

    # 1. .env.local
    ensure_env_local()

    # 2. Firebase emulator config
    ensure_firebase_config()

    # 3. Start emulators
    emulator_proc = start_emulators()

    # 4. Playwright browsers
    ensure_playwright()

    # 5. ffmpeg for GIF conversion
    ensure_ffmpeg()

    # 6. Kill stale dev server on test port
    if check_port(DEV_SERVER_PORT):
        log(f"Killing stale process on port {DEV_SERVER_PORT}")
        kill_port(DEV_SERVER_PORT)

    # Summary
    print()
    log("E2E environment ready! Run tests with:")
    print(f"  cd {PLATFORM_UI}")
    print(f"  NEXT_PUBLIC_USE_EMULATORS=true pnpm test:e2e:auth")
    print()
    print(f"  # With recording + GIFs:")
    print(f"  NEXT_PUBLIC_USE_EMULATORS=true pnpm test:e2e:gif")
    print()

    if emulator_proc is not None:
        log(f"Emulators running (PID {emulator_proc.pid}). Kill with: kill {emulator_proc.pid}")


if __name__ == "__main__":
    main()
