#!/usr/bin/env python3
"""Bootstrap development environment for new developers.

Creates .env.local with demo credentials and starts Firebase emulators.
Run once before starting the dev server.

Usage:
    python3 packages/platform-ui/scripts/bootstrap-dev.py
    
Then:
    pnpm seed:dev
    NEXT_PUBLIC_USE_EMULATORS=true pnpm dev:ui
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

PLATFORM_UI = Path(__file__).resolve().parent.parent
ROOT = PLATFORM_UI.parent.parent
ENV_LOCAL = PLATFORM_UI / ".env.local"
FIREBASE_CONFIG = Path("/tmp/firebase-dev.json")

AUTH_PORT = 9099
FIRESTORE_PORT = 8080

GREEN = "\033[92m"
YELLOW = "\033[93m"
RESET = "\033[0m"
BOLD = "\033[1m"


def log(msg: str, color: str = GREEN) -> None:
    print(f"{color}{BOLD}[bootstrap]{RESET} {msg}")


def check_port(port: int) -> bool:
    """Check if a port is already in use."""
    import urllib.request
    try:
        urllib.request.urlopen(f"http://127.0.0.1:{port}", timeout=2)
        return True
    except Exception:
        return False


def ensure_env_local() -> bool:
    """Create .env.local with demo Firebase credentials if missing."""
    if ENV_LOCAL.exists():
        log(f".env.local already exists at {ENV_LOCAL}", YELLOW)
        return False

    ENV_LOCAL.write_text(
        "# Firebase emulator mode — demo credentials\n"
        "# Auto-generated by bootstrap-dev.py. Safe to delete.\n"
        "NEXT_PUBLIC_FIREBASE_API_KEY=fake-api-key-for-emulators\n"
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-mediforce.firebaseapp.com\n"
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-mediforce\n"
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-mediforce.appspot.com\n"
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000\n"
        "NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000\n"
        "OPENROUTER_API_KEY=fake-openrouter-key\n"
        "PLATFORM_API_KEY=test-api-key\n"
    )
    log(f"Created {ENV_LOCAL} with demo credentials")
    return True


def ensure_firebase_config() -> None:
    """Create Firebase emulator config without UI."""
    config = {
        "firestore": {"rules": "firestore.rules"},
        "emulators": {
            "auth": {"port": AUTH_PORT},
            "firestore": {"port": FIRESTORE_PORT},
            "ui": {"enabled": False},
        },
    }
    FIREBASE_CONFIG.write_text(json.dumps(config, indent=2))
    log(f"Firebase emulator config written to {FIREBASE_CONFIG}")


def start_emulators() -> subprocess.Popen[bytes] | None:
    """Start Firebase emulators if not already running."""
    if check_port(AUTH_PORT) and check_port(FIRESTORE_PORT):
        log("Firebase emulators already running", YELLOW)
        return None

    if not shutil.which("firebase"):
        log("firebase CLI not found — install with: npm i -g firebase-tools", "\033[91m")
        sys.exit(1)

    log("Starting Firebase emulators (auth + firestore)...")
    proc = subprocess.Popen(
        [
            "firebase",
            "emulators:start",
            "--project", "demo-mediforce",
            "--only", "auth,firestore",
            "--config", str(FIREBASE_CONFIG),
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return proc


def main() -> None:
    log("Bootstrapping development environment...")

    created_env = ensure_env_local()
    ensure_firebase_config()
    proc = start_emulators()

    if proc:
        log("Waiting for emulators to start...")
        import time
        for _ in range(30):
            if check_port(AUTH_PORT) and check_port(FIRESTORE_PORT):
                break
            time.sleep(0.5)
        else:
            log("Emulators didn't start within 15s", "\033[91m")
            proc.kill()
            sys.exit(1)

    log("Development environment ready!")
    print()
    if created_env:
        print("Next steps:")
        print("  1. Seed demo data:")
        print("     cd packages/platform-ui && pnpm seed:dev")
        print()
        print("  2. Start the app:")
        print("     NEXT_PUBLIC_USE_EMULATORS=true pnpm dev:ui")
        print()
        print("  3. Sign in with demo credentials:")
        print("     Email: test@mediforce.dev")
        print("     Password: test123456")
    else:
        print("Demo credentials:")
        print("  Email: test@mediforce.dev")
        print("  Password: test123456")
        print()
        print("Start the app:")
        print("  NEXT_PUBLIC_USE_EMULATORS=true pnpm dev:ui")


if __name__ == "__main__":
    main()