/**
 * Shared helpers for sandboxed iframe rendering of agent-produced HTML
 * reports. Used by:
 *   - agent-output-review-panel.tsx (L3 review tasks)
 *   - task-context-panel.tsx (human-review tasks following an agent step)
 *
 * Both consumers render the document inside `<iframe sandbox="allow-scripts">`
 * with an auto-resize listener and theme sync. The helpers below produce the
 * srcdoc and document the message contract so the listeners stay symmetric.
 */

/**
 * Hard cap for the iframe's reported content height, in pixels.
 *
 * The parent grows the iframe to fit content (see `IframeResizeMessage`).
 * Without a cap, agent HTML that uses viewport-relative sizing (Tailwind
 * `min-h-screen`, raw `100vh`, etc.) creates a feedback loop: the iframe is
 * its own viewport, so `100vh` resolves to the current iframe height —
 * growing the iframe enlarges `100vh`, which enlarges `body.scrollHeight`,
 * which re-fires `ResizeObserver`, which grows the iframe again. The cap
 * stops that runaway: beyond this height, the iframe gets its own scrollbar.
 *
 * 2400px ≈ 2× a typical 1200px viewport — long reports still render inline
 * before the iframe falls back to its own scrollbar.
 */
export const MAX_IFRAME_HEIGHT = 2400;

/** Clamp a reported iframe height to the safe range. */
export function clampIframeHeight(height: number): number {
  if (!Number.isFinite(height) || height <= 0) return 0;
  return Math.min(height, MAX_IFRAME_HEIGHT);
}

/**
 * Build a self-contained HTML document for a sandboxed iframe.
 *
 * The document:
 *   - Loads Tailwind v4 from CDN so agent-authored markup can use utility
 *     classes without a build step.
 *   - Exposes the structured agent result (if any) on `window.__data__`.
 *   - Posts `{ type: 'resize', height }` to the parent on every body resize so
 *     the parent can size the iframe to fit content.
 *   - Listens for `{ type: 'theme', dark }` messages from the parent and
 *     toggles the `dark` class on `<html>` to keep the iframe in step with
 *     the host theme.
 *   - Neutralises Tailwind's viewport-relative height classes so agent HTML
 *     written with `h-screen` / `min-h-screen` does not chase the iframe
 *     viewport in a resize feedback loop (see `MAX_IFRAME_HEIGHT`).
 */
export function buildSrcdoc(presentation: string, result: Record<string, unknown> | null, isDark: boolean): string {
  const csp = [
    "default-src 'none'",
    "script-src 'unsafe-inline' https://cdn.jsdelivr.net",
    "style-src 'unsafe-inline'",
    'img-src data: blob:',
    'font-src data:',
    'media-src data: blob:',
    "connect-src 'none'",
    "frame-src 'none'",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'none'",
  ].join('; ');

  // Escape closing script tags in data to prevent XSS breakout. JSON.stringify
  // throws on circular refs — agents are unlikely to produce one, but instead
  // of silently degrading to `{}` (which looks like a normal "no data" case)
  // we surface the failure as `window.__data__._error` so the presenter can
  // distinguish it from a missing payload.
  let safeData: string;
  try {
    safeData = JSON.stringify(result ?? {}).replace(/<\//g, '<\\/');
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'unknown error';
    console.warn('[iframe-helpers] result not JSON-serialisable:', err);
    safeData = JSON.stringify({ _error: `result not serialisable: ${msg}` }).replace(/<\//g, '<\\/');
  }
  return `<!DOCTYPE html>
<html class="${isDark ? 'dark' : ''}">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
<style type="text/tailwindcss">
@theme {
  --color-surface: #ffffff;
  --color-surface-dark: #0f1117;
  --color-text: #1a1a2e;
  --color-text-dark: #e2e4e9;
  --color-muted: #6b7280;
  --color-muted-dark: #9ca3af;
  --color-border: #e5e7eb;
  --color-border-dark: #2d2f36;
}
body {
  margin: 0;
  padding: 1rem;
  background: var(--color-surface);
  color: var(--color-text);
}
.dark body {
  background: var(--color-surface-dark);
  color: var(--color-text-dark);
}
</style>
<!--
  Neutralise viewport-relative heights AFTER the @tailwindcss block so this
  plain <style> rule beats any utility generated by the CDN runtime. !important
  guards against equal-specificity ties — the agent's HTML class wins the
  cascade otherwise once Tailwind injects its own .h-screen utility.

  Note: inline style="height:100vh" on agent markup is NOT covered here.
  The parent-side MAX_IFRAME_HEIGHT clamp is the sole defence for that path.
-->
<style>
.h-screen, .min-h-screen, .max-h-screen {
  height: auto !important;
  min-height: 0 !important;
  max-height: none !important;
}
</style>
<script>window.__data__ = ${safeData};</script>
</head>
<body>
${presentation}
<script>
// Sandboxed iframes without allow-same-origin get a null origin, so
// postMessage cannot use a concrete target — '*' is the only valid value
// here. The parent verifies inbound messages with
// event.source === iframeRef.current.contentWindow.
const ro = new ResizeObserver(() => {
  window.parent.postMessage({ type: 'resize', height: document.body.scrollHeight }, '*');
});
ro.observe(document.body);
window.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'theme') {
    document.documentElement.classList.toggle('dark', e.data.dark);
  }
});
</script>
</body>
</html>`;
}

/** Message posted by the iframe when its body size changes. */
export interface IframeResizeMessage {
  type: 'resize';
  height: number;
}

/** Type guard for iframe-originated resize messages. */
export function isIframeResizeMessage(data: unknown): data is IframeResizeMessage {
  return (
    data !== null &&
    typeof data === 'object' &&
    (data as { type?: unknown }).type === 'resize' &&
    typeof (data as { height?: unknown }).height === 'number'
  );
}
