import { z } from 'zod';

/**
 * Hard ceiling for attachment size in bytes (100 MiB, ADR-0003 §4). Mirrored by
 * the Postgres `attachment_size_guard` CHECK; the `MEDIFORCE_ATTACHMENT_MAX_BYTES`
 * env knob may only LOWER this, never raise it above the DB ceiling.
 */
export const ATTACHMENT_MAX_BYTES = 104_857_600;

/**
 * Metadata for a file attached to a Human Task (ADR-0003). The bytes live in a
 * `BlobStore` keyed by `blobKey`; only this metadata row is in Postgres.
 *
 * `workspace` is carried directly (FK → `workspaces.handle`) so reads are
 * workspace-gated without a parent lookup — unlike HumanTask, which resolves
 * its namespace via the parent ProcessInstance.
 *
 * `uploadedBy` is a Firebase uid `text` with no FK: ADR-0002 (auth) lands
 * after this ADR, so there is no `auth_users` table to reference yet.
 *
 * Soft-delete via `deletedAt` (null = active). DELETE flags the row and keeps
 * the blob; blob garbage-collection is a later sweep (ADR-0003 §7).
 */
export const TaskAttachmentSchema = z.object({
  id: z.string().uuid(),
  taskId: z.string().min(1),
  workspace: z.string().min(1),
  name: z.string().min(1),
  contentType: z.string().min(1),
  sizeBytes: z.number().int().nonnegative(),
  blobKey: z.string().min(1),
  uploadedBy: z.string().min(1),
  uploadedAt: z.string().datetime(),
  deletedAt: z.string().datetime().nullable(),
});

/**
 * Fields a caller supplies on create. `id` and `uploadedAt` are generated by
 * the repository; `deletedAt` starts null.
 */
export const NewTaskAttachmentSchema = TaskAttachmentSchema.omit({
  id: true,
  uploadedAt: true,
  deletedAt: true,
});

export type TaskAttachment = z.infer<typeof TaskAttachmentSchema>;
export type NewTaskAttachment = z.infer<typeof NewTaskAttachmentSchema>;
