const now = new Date().toISOString();
const oneHourAgo = new Date(Date.now() - 3600_000).toISOString();
const twoDaysAgo = new Date(Date.now() - 2 * 86400_000).toISOString();
const threeDaysAgo = new Date(Date.now() - 3 * 86400_000).toISOString();
const nextWeek = new Date(Date.now() + 7 * 86400_000).toISOString();

export function buildSeedData(testUserId: string) {
  const humanTasks: Record<string, Record<string, unknown>> = {
    'task-pending-1': {
      id: 'task-pending-1',
      processInstanceId: 'proc-running-1',
      stepId: 'review-intake-data',
      assignedRole: 'reviewer',
      assignedUserId: null,
      status: 'pending',
      deadline: nextWeek,
      createdAt: oneHourAgo,
      updatedAt: oneHourAgo,
      completedAt: null,
      completionData: null,
    },
    'task-claimed-1': {
      id: 'task-claimed-1',
      processInstanceId: 'proc-running-1',
      stepId: 'approve-report',
      assignedRole: 'reviewer',
      assignedUserId: testUserId,
      status: 'claimed',
      deadline: nextWeek,
      createdAt: oneHourAgo,
      updatedAt: now,
      completedAt: null,
      completionData: null,
    },
    'task-completed-1': {
      id: 'task-completed-1',
      processInstanceId: 'proc-completed-1',
      stepId: 'verify-data-quality',
      assignedRole: 'reviewer',
      assignedUserId: testUserId,
      status: 'completed',
      deadline: null,
      createdAt: threeDaysAgo,
      updatedAt: twoDaysAgo,
      completedAt: twoDaysAgo,
      completionData: { approved: true, notes: 'All checks passed' },
    },
    'task-pending-2': {
      id: 'task-pending-2',
      processInstanceId: 'proc-paused-1',
      stepId: 'assess-supplier-risk',
      assignedRole: 'analyst',
      assignedUserId: null,
      status: 'pending',
      deadline: nextWeek,
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
      completedAt: null,
      completionData: null,
    },
    'task-human-review': {
      id: 'task-human-review',
      processInstanceId: 'proc-human-waiting',
      stepId: 'human-review',
      assignedRole: 'reviewer',
      assignedUserId: null,
      status: 'pending',
      deadline: nextWeek,
      createdAt: now,
      updatedAt: now,
      completedAt: null,
      completionData: null,
    },
    'task-upload-docs': {
      id: 'task-upload-docs',
      processInstanceId: 'proc-upload-waiting',
      stepId: 'upload-documents',
      assignedRole: 'operator',
      assignedUserId: testUserId,
      status: 'claimed',
      deadline: nextWeek,
      createdAt: now,
      updatedAt: now,
      completedAt: null,
      completionData: null,
      ui: {
        component: 'file-upload',
        config: {
          acceptedTypes: ['application/pdf'],
          minFiles: 1,
          maxFiles: 5,
        },
      },
    },
  };

  const processInstances: Record<string, Record<string, unknown>> = {
    'proc-running-1': {
      id: 'proc-running-1',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1.0.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'running',
      currentStepId: 'narrative-summary',
      variables: { studyId: 'study-001', cycle: 3 },
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: oneHourAgo,
      updatedAt: now,
      createdBy: 'system',
      pauseReason: null,
      error: null,
      assignedRoles: ['reviewer'],
    },
    // Dedicated instance for cancel-run test — isolated so cancelling doesn't affect other tests
    'proc-cancel-target': {
      id: 'proc-cancel-target',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1.0.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'running',
      currentStepId: 'narrative-summary',
      variables: {},
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: oneHourAgo,
      updatedAt: now,
      createdBy: 'system',
      pauseReason: null,
      error: null,
      assignedRoles: ['reviewer'],
    },
    'proc-paused-1': {
      id: 'proc-paused-1',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1.0.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'paused',
      currentStepId: 'data-quality-check',
      variables: { studyId: 'study-002' },
      triggerType: 'webhook',
      triggerPayload: { source: 'edc-system' },
      createdAt: twoDaysAgo,
      updatedAt: oneHourAgo,
      createdBy: 'webhook',
      pauseReason: 'agent_escalation',
      error: null,
      assignedRoles: ['analyst', 'reviewer'],
    },
    'proc-completed-1': {
      id: 'proc-completed-1',
      definitionName: 'Data Quality Review',
      definitionVersion: '2.1.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'completed',
      currentStepId: null,
      variables: { studyId: 'study-001' },
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: threeDaysAgo,
      updatedAt: twoDaysAgo,
      createdBy: testUserId,
      pauseReason: null,
      error: null,
      assignedRoles: ['reviewer'],
    },
    'proc-failed-1': {
      id: 'proc-failed-1',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1.0.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'failed',
      currentStepId: 'compliance-check',
      variables: {},
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: threeDaysAgo,
      updatedAt: threeDaysAgo,
      createdBy: 'system',
      pauseReason: null,
      error: 'Agent timeout after 30s',
      assignedRoles: [],
    },
    'proc-completed-2': {
      id: 'proc-completed-2',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1.0.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'completed',
      currentStepId: null,
      variables: { studyId: 'study-004' },
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: threeDaysAgo,
      updatedAt: twoDaysAgo,
      createdBy: testUserId,
      pauseReason: null,
      error: null,
      assignedRoles: ['reviewer'],
    },
    'proc-human-waiting': {
      id: 'proc-human-waiting',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1.0.0',
      configName: 'all-human',
      configVersion: '1',
      status: 'paused',
      currentStepId: 'human-review',
      variables: { studyId: 'study-003' },
      triggerType: 'manual',
      triggerPayload: { studyId: 'study-003' },
      createdAt: oneHourAgo,
      updatedAt: now,
      createdBy: 'auto-runner',
      pauseReason: 'waiting_for_human',
      error: null,
      assignedRoles: ['reviewer'],
    },
    // New-style run — uses WorkflowDefinition (no configName/configVersion)
    'proc-workflow-run-1': {
      id: 'proc-workflow-run-1',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1',
      status: 'running',
      currentStepId: 'narrative-summary',
      variables: { studyId: 'study-wf-001' },
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: oneHourAgo,
      updatedAt: now,
      createdBy: testUserId,
      pauseReason: null,
      error: null,
      assignedRoles: ['reviewer'],
    },
    'proc-upload-waiting': {
      id: 'proc-upload-waiting',
      definitionName: 'Protocol to TFL',
      definitionVersion: '0.1.0',
      configName: 'default',
      configVersion: '1',
      status: 'paused',
      currentStepId: 'upload-documents',
      variables: {},
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: now,
      updatedAt: now,
      createdBy: testUserId,
      pauseReason: 'waiting_for_human',
      error: null,
      assignedRoles: ['operator'],
    },
    // Dedicated instance for retry-step test — seeded as failed on a human step
    // so clicking Retry flips it to running; the auto-runner then creates a
    // HumanTask and pauses the instance. No plugin or Docker involved.
    'proc-retry-test': {
      id: 'proc-retry-test',
      definitionName: 'Supply Chain Review',
      definitionVersion: '1',
      status: 'failed',
      currentStepId: 'human-review',
      variables: {},
      triggerType: 'manual',
      triggerPayload: {},
      createdAt: threeDaysAgo,
      updatedAt: threeDaysAgo,
      createdBy: testUserId,
      pauseReason: null,
      error: 'Simulated step failure for retry journey',
      assignedRoles: ['reviewer'],
    },
  };

  const agentRuns: Record<string, Record<string, unknown>> = {
    'run-completed-1': {
      id: 'run-completed-1',
      processInstanceId: 'proc-running-1',
      stepId: 'narrative-summary',
      pluginId: 'narrative-summary',
      autonomyLevel: 'L2',
      status: 'completed',
      envelope: {
        model: 'openrouter/anthropic/claude-sonnet-4',
        confidence: 0.92,
        confidence_rationale: 'Routine review of 12 well-structured vendor submissions. All fields present, no ambiguities. Expected error rate below 1 in 10.',
        reasoning_summary: 'Reviewed 12 vendor submissions. No issues detected. All items within expected parameters.',
        reasoning_chain: [],
        duration_ms: 1200,
        result: { issuesFound: 0, reviewedItems: 12, recommendation: 'continue' },
        annotations: [],
      },
      fallbackReason: null,
      startedAt: oneHourAgo,
      completedAt: now,
      executorType: 'agent',
      reviewerType: 'none',
    },
    'run-escalated-1': {
      id: 'run-escalated-1',
      processInstanceId: 'proc-paused-1',
      stepId: 'data-quality-check',
      pluginId: 'data-quality',
      autonomyLevel: 'L3',
      status: 'escalated',
      envelope: {
        model: 'openrouter/anthropic/claude-sonnet-4',
        confidence: 0.45,
        confidence_rationale: 'Multiple data inconsistencies in lab values — 3 out of 7 fields required interpolation from incomplete source data. In ~6/10 similar cases, at least one critical issue would be missed.',
        reasoning_summary: 'Multiple data inconsistencies found in lab values. Requires human review.',
        reasoning_chain: [],
        duration_ms: 3500,
        result: { issuesFound: 7, criticalIssues: 2 },
        annotations: [],
      },
      fallbackReason: 'low_confidence',
      startedAt: twoDaysAgo,
      completedAt: twoDaysAgo,
      executorType: 'agent',
      reviewerType: 'human',
    },
    'run-running-1': {
      id: 'run-running-1',
      processInstanceId: 'proc-running-1',
      stepId: 'compliance-check',
      pluginId: 'compliance-check',
      autonomyLevel: 'L1',
      status: 'running',
      envelope: null,
      fallbackReason: null,
      startedAt: now,
      completedAt: null,
      executorType: 'agent',
    },
    'run-l4-autopilot': {
      id: 'run-l4-autopilot',
      processInstanceId: 'proc-completed-2',
      stepId: 'vendor-assessment',
      pluginId: 'vendor-assessment',
      autonomyLevel: 'L4',
      status: 'completed',
      envelope: {
        model: 'openrouter/anthropic/claude-sonnet-4',
        confidence: 0.97,
        confidence_rationale: 'Standard vendor assessment with complete metrics. All values within established norms. Fewer than 3 in 100 similar cases would surface an issue.',
        reasoning_summary: 'All metrics within expected range. Auto-approved.',
        reasoning_chain: [],
        duration_ms: 800,
        result: { issuesFound: 0, autoApproved: true },
        annotations: [],
      },
      fallbackReason: null,
      startedAt: twoDaysAgo,
      completedAt: twoDaysAgo,
      executorType: 'agent',
      reviewerType: 'none',
    },
  };

  const auditEvents: Record<string, Record<string, unknown>> = {
    'audit-1': {
      actorId: 'agent:narrative-summary',
      actorType: 'agent',
      actorRole: 'agent',
      action: 'step.started',
      description: 'Agent started narrative summary step',
      timestamp: oneHourAgo,
      inputSnapshot: { stepId: 'narrative-summary' },
      outputSnapshot: {},
      basis: 'process-definition',
      entityType: 'step-execution',
      entityId: 'exec-1',
      processInstanceId: 'proc-running-1',
      stepId: 'narrative-summary',
      processDefinitionVersion: '1.0.0',
    },
    'audit-2': {
      actorId: 'agent:narrative-summary',
      actorType: 'agent',
      actorRole: 'agent',
      action: 'step.completed',
      description: 'Agent completed narrative summary with confidence 0.92',
      timestamp: now,
      inputSnapshot: { stepId: 'narrative-summary' },
      outputSnapshot: { confidence: 0.92, issuesFound: 0 },
      basis: 'agent-output',
      entityType: 'step-execution',
      entityId: 'exec-1',
      processInstanceId: 'proc-running-1',
      stepId: 'narrative-summary',
      processDefinitionVersion: '1.0.0',
    },
    'audit-3': {
      actorId: 'system',
      actorType: 'system',
      actorRole: 'system',
      action: 'process.completed',
      description: 'Process completed successfully',
      timestamp: twoDaysAgo,
      inputSnapshot: {},
      outputSnapshot: { finalStatus: 'completed' },
      basis: 'workflow-engine',
      entityType: 'process-instance',
      entityId: 'proc-completed-1',
      processInstanceId: 'proc-completed-1',
      processDefinitionVersion: '2.1.0',
    },
  };

  const stepExecutions: Record<string, Record<string, unknown>> = {
    'exec-intake': {
      id: 'exec-intake',
      instanceId: 'proc-running-1',
      stepId: 'vendor-assessment',
      status: 'completed',
      input: { source: 'edc-import' },
      output: { participantsLoaded: 24 },
      verdict: null,
      executedBy: 'system',
      startedAt: oneHourAgo,
      completedAt: oneHourAgo,
      iterationNumber: 0,
      gateResult: { next: 'narrative-summary', reason: 'intake complete' },
      error: null,
    },
    'exec-intake-review': {
      id: 'exec-intake-review',
      instanceId: 'proc-running-1',
      stepId: 'narrative-summary',
      status: 'running',
      input: { participantIds: ['p-001', 'p-002', 'p-003'] },
      output: null,
      verdict: null,
      executedBy: 'agent:intake-review',
      startedAt: now,
      completedAt: null,
      iterationNumber: 0,
      gateResult: null,
      error: null,
    },
  };

  const retryTestStepExecutions: Record<string, Record<string, unknown>> = {
    // Seed a single failed execution so retryStep's latestExecution guard is satisfied
    'exec-retry-fail-1': {
      id: 'exec-retry-fail-1',
      instanceId: 'proc-retry-test',
      stepId: 'human-review',
      status: 'failed',
      input: {},
      output: null,
      verdict: null,
      executedBy: 'auto-runner',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: null,
      error: 'Simulated step failure for retry journey',
    },
  };

  const humanWaitingStepExecutions: Record<string, Record<string, unknown>> = {
    'exec-hw-agent-1': {
      id: 'exec-hw-agent-1',
      instanceId: 'proc-human-waiting',
      stepId: 'query-status',
      status: 'completed',
      input: { studyId: 'study-003' },
      output: {
        reasoning_summary: 'Analyzed 15 open queries across 3 sites. 4 queries are overdue, 2 critical.',
        queriesTotal: 15,
        queriesOverdue: 4,
        queriesCritical: 2,
        sites: ['Site A', 'Site B', 'Site C'],
        recommendation: 'Review overdue queries — 2 critical queries require immediate attention',
      },
      verdict: null,
      executedBy: 'agent:query-status',
      startedAt: oneHourAgo,
      completedAt: now,
      iterationNumber: 0,
      gateResult: { next: 'human-review', reason: 'agent step complete' },
      error: null,
    },
  };

  const processDefinitions: Record<string, Record<string, unknown>> = {
    'def-supply-chain-review': {
      name: 'Supply Chain Review',
      namespace: 'test',
      version: '1.0.0',
      description: 'End-to-end supply chain review process',
      steps: [
        { id: 'vendor-assessment', name: 'Vendor Assessment', type: 'creation' },
        { id: 'narrative-summary', name: 'Narrative Summary', type: 'creation' },
        { id: 'risk-scoring', name: 'Risk Scoring', type: 'creation' },
        { id: 'data-quality', name: 'Data Quality Analysis', type: 'creation' },
        { id: 'query-status', name: 'Query Status Analysis', type: 'creation' },
        { id: 'human-review', name: 'Human Review', type: 'creation' },
        { id: 'manager-approval', name: 'Manager Approval', type: 'review', verdicts: { approve: { target: 'archived' }, 'request-actions': { target: 'archived' } } },
        { id: 'archived', name: 'Archived', type: 'terminal' },
      ],
      transitions: [
        { from: 'vendor-assessment', to: 'narrative-summary' },
        { from: 'narrative-summary', to: 'risk-scoring' },
        { from: 'risk-scoring', to: 'data-quality' },
        { from: 'data-quality', to: 'query-status' },
        { from: 'query-status', to: 'human-review' },
        { from: 'human-review', to: 'manager-approval' },
        { from: 'manager-approval', to: 'archived' },
      ],
      triggers: [{ type: 'manual', name: 'start-review-cycle' }],
    },
    'def-data-quality-review': {
      name: 'Data Quality Review',
      namespace: 'test',
      version: '2.1.0',
      description: 'Data quality check workflow',
      steps: [
        { id: 'verify-data-quality', name: 'Verify Data Quality', type: 'creation' },
        { id: 'review-results', name: 'Review Results', type: 'creation' },
        { id: 'done', name: 'Done', type: 'terminal' },
      ],
      transitions: [
        { from: 'verify-data-quality', to: 'review-results' },
        { from: 'review-results', to: 'done' },
      ],
      triggers: [{ type: 'manual', name: 'start-review' }],
    },
  };

  const completedProcessStepExecutions: Record<string, Record<string, unknown>> = {
    'exec-dq-verify': {
      id: 'exec-dq-verify',
      instanceId: 'proc-completed-1',
      stepId: 'verify-data-quality',
      status: 'completed',
      input: { studyId: 'study-001' },
      output: { issuesFound: 0, allChecksPass: true },
      verdict: null,
      executedBy: 'agent:data-quality',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'review-results', reason: 'quality check complete' },
      error: null,
    },
    'exec-dq-review': {
      id: 'exec-dq-review',
      instanceId: 'proc-completed-1',
      stepId: 'review-results',
      status: 'completed',
      input: { issuesFound: 0 },
      output: { approved: true, notes: 'All checks passed' },
      verdict: null,
      executedBy: 'test-user',
      startedAt: threeDaysAgo,
      completedAt: twoDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'done', reason: 'review complete' },
      error: null,
    },
  };

  const completedSupplyChainStepExecutions: Record<string, Record<string, unknown>> = {
    'exec-cm-spp': {
      id: 'exec-cm-spp',
      instanceId: 'proc-completed-2',
      stepId: 'vendor-assessment',
      status: 'completed',
      input: { studyId: 'study-004' },
      output: { participantsReviewed: 18 },
      verdict: null,
      executedBy: 'agent:vendor-assessment',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'narrative-summary', reason: 'vendor assessment complete' },
      error: null,
    },
    'exec-cm-ns': {
      id: 'exec-cm-ns',
      instanceId: 'proc-completed-2',
      stepId: 'narrative-summary',
      status: 'completed',
      input: { participantsReviewed: 18 },
      output: { summaryGenerated: true },
      verdict: null,
      executedBy: 'agent:narrative-summary',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'risk-scoring', reason: 'narrative complete' },
      error: null,
    },
    'exec-cm-spa': {
      id: 'exec-cm-spa',
      instanceId: 'proc-completed-2',
      stepId: 'risk-scoring',
      status: 'completed',
      input: { summaryGenerated: true },
      output: { populationSafe: true },
      verdict: null,
      executedBy: 'agent:risk-scoring',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'data-quality', reason: 'population analysis complete' },
      error: null,
    },
    'exec-cm-dq': {
      id: 'exec-cm-dq',
      instanceId: 'proc-completed-2',
      stepId: 'data-quality',
      status: 'completed',
      input: { populationSafe: true },
      output: { issuesFound: 0 },
      verdict: null,
      executedBy: 'agent:data-quality',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'query-status', reason: 'data quality check complete' },
      error: null,
    },
    'exec-cm-qs': {
      id: 'exec-cm-qs',
      instanceId: 'proc-completed-2',
      stepId: 'query-status',
      status: 'completed',
      input: { issuesFound: 0 },
      output: { openQueries: 0 },
      verdict: null,
      executedBy: 'agent:query-status',
      startedAt: threeDaysAgo,
      completedAt: threeDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'human-review', reason: 'query status complete' },
      error: null,
    },
    'exec-cm-hr': {
      id: 'exec-cm-hr',
      instanceId: 'proc-completed-2',
      stepId: 'human-review',
      status: 'completed',
      input: { openQueries: 0 },
      output: { reviewed: true },
      verdict: null,
      executedBy: testUserId,
      startedAt: threeDaysAgo,
      completedAt: twoDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'manager-approval', reason: 'human review complete' },
      error: null,
    },
    'exec-cm-ma': {
      id: 'exec-cm-ma',
      instanceId: 'proc-completed-2',
      stepId: 'manager-approval',
      status: 'completed',
      input: { reviewed: true },
      output: { verdict: 'approve', comment: 'All looks good' },
      verdict: 'approve',
      executedBy: testUserId,
      startedAt: twoDaysAgo,
      completedAt: twoDaysAgo,
      iterationNumber: 0,
      gateResult: { next: 'archived', reason: 'Approved by manager' },
      error: null,
    },
  };

  const processConfigs: Record<string, Record<string, unknown>> = {
    'Supply Chain Review:all-human:1': {
      processName: 'Supply Chain Review',
      configName: 'all-human',
      configVersion: '1',
      stepConfigs: [
        { stepId: 'vendor-assessment', executorType: 'agent', autonomyLevel: 'L4', plugin: 'supply-chain/vendor-assessment' },
        { stepId: 'narrative-summary', executorType: 'agent', autonomyLevel: 'L2', plugin: 'supply-chain/narrative-summary' },
        { stepId: 'risk-scoring', executorType: 'agent', autonomyLevel: 'L3', plugin: 'supply-chain/risk-scoring', reviewerType: 'human' },
        { stepId: 'data-quality', executorType: 'agent', autonomyLevel: 'L2', plugin: 'supply-chain/data-quality' },
        { stepId: 'query-status', executorType: 'agent', autonomyLevel: 'L1', plugin: 'supply-chain/query-status' },
        { stepId: 'human-review', executorType: 'human' },
        { stepId: 'manager-approval', executorType: 'human' },
      ],
    },
  };

  // User profile document — required by Firestore security rules.
  // humanTasks and handoffEntities rules call get(/users/{uid}).data.roles
  // to verify the reader has a matching role.
  const users: Record<string, Record<string, unknown>> = {
    [testUserId]: {
      uid: testUserId,
      email: 'test@mediforce.dev',
      displayName: 'Test User',
      handle: 'test',
      organizations: [],
      role: 'admin',
      roles: ['reviewer', 'analyst', 'operator'],
    },
  };

  const workflowDefinitions: Record<string, Record<string, unknown>> = {
    'Supply Chain Review:1': {
      name: 'Supply Chain Review',
      namespace: 'test',
      version: 1,
      title: 'Initial vendor assessment workflow',
      description: 'End-to-end supply chain review process',
      steps: [
        { id: 'vendor-assessment', name: 'Vendor Assessment', type: 'creation', executor: 'agent', autonomyLevel: 'L2', plugin: 'supply-data-collector', agent: { skill: 'vendor-assessment', mcpServers: [{ name: 'postgres-ro', command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres'], env: { DATABASE_URL: '{{DB_URL}}' }, allowedTools: ['query'] }, { name: 'filesystem', command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '/data'] }] } },
        { id: 'narrative-summary', name: 'Narrative Summary', type: 'creation', executor: 'agent', autonomyLevel: 'L3' },
        { id: 'risk-scoring', name: 'Risk Scoring', type: 'creation', executor: 'agent', autonomyLevel: 'L2' },
        { id: 'human-review', name: 'Human Review', type: 'review', executor: 'human', verdicts: { approve: { target: 'done' }, revise: { target: 'vendor-assessment' } } },
        { id: 'done', name: 'Done', type: 'terminal', executor: 'human' },
      ],
      transitions: [
        { from: 'vendor-assessment', to: 'narrative-summary' },
        { from: 'narrative-summary', to: 'risk-scoring' },
        { from: 'risk-scoring', to: 'human-review' },
      ],
      triggers: [{ type: 'manual', name: 'start-review-cycle' }],
      createdAt: twoDaysAgo,
    },
  };

  const agentDefinitions: Record<string, Record<string, unknown>> = {
    'agent-def-driver': {
      id: 'agent-def-driver',
      pluginId: 'supply-intelligence/driver-agent',
      name: 'Driver Agent',
      iconName: 'Chart',
      description: 'Orchestrates multi-step supply chain review workflows by coordinating data collection, analysis, and reporting agents.',
      inputDescription: 'Workflow trigger payload with study identifiers',
      outputDescription: 'Completed workflow result with step summaries',
      foundationModel: 'anthropic/claude-sonnet-4',
      systemPrompt: '',
      skillFileNames: [],
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },
    'agent-def-risk-detection': {
      id: 'agent-def-risk-detection',
      pluginId: 'supply-intelligence/risk-detection',
      name: 'Risk Detection',
      iconName: 'Chart',
      description: 'Analyzes vendor submissions and supply chain data to identify potential risks, anomalies, and compliance issues.',
      inputDescription: 'Vendor submission records and historical data',
      outputDescription: 'Risk scores, flagged issues, and recommendations',
      foundationModel: 'anthropic/claude-sonnet-4',
      systemPrompt: '',
      skillFileNames: [],
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },
    'agent-def-claude-code': {
      id: 'agent-def-claude-code',
      pluginId: 'claude-code-agent',
      name: 'Claude Code Agent',
      iconName: 'Bot',
      description: 'Executes code generation, analysis, and automated software tasks using Claude\'s advanced coding capabilities.',
      inputDescription: 'Task description and relevant code context',
      outputDescription: 'Generated code, analysis results, or task completion report',
      foundationModel: 'anthropic/claude-sonnet-4',
      systemPrompt: '',
      skillFileNames: [],
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },
    'agent-def-opencode': {
      id: 'agent-def-opencode',
      pluginId: 'opencode-agent',
      name: 'OpenCode Agent',
      iconName: 'Cpu',
      description: 'Open-source code execution agent powered by DeepSeek for cost-efficient automated development tasks.',
      inputDescription: 'Code task description and project context',
      outputDescription: 'Implemented code changes and execution results',
      foundationModel: 'deepseek/deepseek-chat',
      systemPrompt: '',
      skillFileNames: [],
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },
    'agent-def-script-container': {
      id: 'agent-def-script-container',
      pluginId: 'script-container',
      name: 'Script Container',
      iconName: 'Terminal',
      description: 'Sandboxed execution environment for running custom scripts, data transformations, and automation tasks.',
      inputDescription: 'Script definition and input parameters',
      outputDescription: 'Script execution output and exit status',
      foundationModel: 'anthropic/claude-sonnet-4',
      systemPrompt: '',
      skillFileNames: [],
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },
  };

  const namespaces: Record<string, Record<string, unknown>> = {
    test: {
      id: 'test',
      handle: 'test',
      type: 'personal',
      displayName: 'Test User',
      linkedUserId: testUserId,
      createdAt: '2024-01-01T00:00:00.000Z',
    },
  };

  const namespaceMembers: Record<string, Record<string, unknown>> = {
    [testUserId]: {
      id: testUserId,
      uid: testUserId,
      role: 'owner',
      joinedAt: '2024-01-01T00:00:00.000Z',
    },
  };

  // -------------------------------------------------------------------------
  // Cowork sessions — collaborative human+AI artifact building
  // -------------------------------------------------------------------------

  const coworkSessions: Record<string, Record<string, unknown>> = {
    'cowork-active-1': {
      id: 'cowork-active-1',
      processInstanceId: 'proc-cowork-paused',
      stepId: 'design',
      assignedRole: 'analyst',
      assignedUserId: testUserId,
      status: 'active',
      agent: 'chat',
      model: 'anthropic/claude-sonnet-4',
      systemPrompt: 'You are a workflow design assistant.',
      outputSchema: {
        type: 'object',
        required: ['name', 'description', 'steps'],
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          steps: { type: 'array' },
        },
      },
      voiceConfig: null,
      artifact: {
        name: 'data-quality-review',
        description: 'Automated data quality review workflow',
        steps: [
          { id: 'collect', name: 'Collect Data', executor: 'script' },
          { id: 'analyze', name: 'Analyze Quality', executor: 'agent' },
          { id: 'review', name: 'Human Review', executor: 'human' },
        ],
      },
      turns: [
        {
          id: 'turn-1',
          role: 'human',
          content: 'I need a workflow for automated data quality review with 3 steps: collect data, analyze quality, and human review.',
          timestamp: oneHourAgo,
          artifactDelta: null,
        },
        {
          id: 'turn-2',
          role: 'agent',
          content: 'I\'ve drafted a 3-step workflow: data collection via script, AI-powered quality analysis, and a final human review gate. The artifact has been updated with the full structure.',
          timestamp: oneHourAgo,
          artifactDelta: {
            name: 'data-quality-review',
            description: 'Automated data quality review workflow',
            steps: [
              { id: 'collect', name: 'Collect Data', executor: 'script' },
              { id: 'analyze', name: 'Analyze Quality', executor: 'agent' },
              { id: 'review', name: 'Human Review', executor: 'human' },
            ],
          },
        },
      ],
      createdAt: oneHourAgo,
      updatedAt: oneHourAgo,
      finalizedAt: null,
    },
  };

  // Process instance paused for cowork
  processInstances['proc-cowork-paused'] = {
    id: 'proc-cowork-paused',
    definitionName: 'Workflow Designer',
    definitionVersion: '1',
    status: 'paused',
    currentStepId: 'design',
    variables: {},
    triggerType: 'manual',
    triggerPayload: {},
    createdAt: oneHourAgo,
    updatedAt: oneHourAgo,
    createdBy: testUserId,
    pauseReason: 'cowork_in_progress',
    error: null,
    assignedRoles: ['analyst'],
  };

  // Workflow definition with a cowork step
  workflowDefinitions['Workflow Designer:1'] = {
    name: 'Workflow Designer',
    namespace: 'test',
    version: 1,
    description: 'Collaboratively design workflows with AI',
    steps: [
      {
        id: 'design',
        name: 'Design Workflow',
        type: 'creation',
        executor: 'cowork',
        description: 'Collaboratively build a workflow definition with AI assistance. Describe your requirements and iterate on the design.',
        allowedRoles: ['analyst'],
        cowork: {
          agent: 'chat',
          systemPrompt: 'You are a workflow design assistant.',
          outputSchema: {
            type: 'object',
            required: ['name', 'description', 'steps'],
            properties: {
              name: { type: 'string' },
              description: { type: 'string' },
              steps: { type: 'array' },
            },
          },
          chat: { model: 'anthropic/claude-sonnet-4' },
        },
      },
      { id: 'done', name: 'Done', type: 'terminal', executor: 'human' },
    ],
    transitions: [{ from: 'design', to: 'done' }],
    triggers: [{ type: 'manual', name: 'start-design' }],
    createdAt: twoDaysAgo,
  };

  return { users, humanTasks, processInstances, agentRuns, auditEvents, stepExecutions, humanWaitingStepExecutions, retryTestStepExecutions, processDefinitions, completedProcessStepExecutions, completedSupplyChainStepExecutions, processConfigs, workflowDefinitions, agentDefinitions, namespaces, namespaceMembers, coworkSessions };
}
